Update patch set 2
Patch Set 2:

> On my side, I have an issue when building it with Gerrit's HEAD:
 > ERROR: /home/edebanne/repos/gerrit/plugins/autosubmitter/BUILD:4:1:
 > Building plugins/autosubmitter/libautosubmitter__plugin.jar (5
 > source files) failed: Worker process sent response with exit code:
 > 1.
 > plugins/autosubmitter/src/main/java/com/criteo/gerrit/plugins/automerge/AtomicityHelper.java:118:
 > error: SubmitRuleEvaluator(AccountCache,Accounts,Emails,ChangeData)
 > is not public in SubmitRuleEvaluator; cannot be accessed from
 > outside package

Gah, that's because of [1] that was merged in the meantime.

Another fix is required.

[1] https://gerrit-review.googlesource.com/?polygerrit=0#/c/gerrit/+/127375/

Patch-set: 2
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>