Update patch set 4
Patch Set 4:

Building this, i now get

plugins/autosubmitter/src/main/java/com/criteo/gerrit/plugins/automerge/AtomicityHelper.java:151: error: cannot find symbol
    ChangeControl ctl = changeFactory.validateFor(db.get(), new Change.Id(changeNumber), getBotUser());
                                     ^
  symbol:   method validateFor(ReviewDb,Id,IdentifiedUser)
  location: variable changeFactory of type GenericFactory
Target //plugins/autosubmitter:autosubmitter failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.863s, Critical Path: 1.53s
                                              ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
Target //plugins/autosubmitter:autosubmitter failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.398s, Critical Path: 0.25s

which is caused by https://gerrit-review.googlesource.com/#/c/gerrit/+/121353/

changing it, i now get

ERROR: /Users/patrickmulhall/Documents/workspace/gerrit/plugins/autosubmitter/BUILD:4:1: Building plugins/autosubmitter/libautosubmitter__plugin.jar (5 source files) failed: Worker process sent response with exit code: 1.
plugins/autosubmitter/src/main/java/com/criteo/gerrit/plugins/automerge/AtomicityHelper.java:163: error: incompatible types: ChangeNotes cannot be converted to ChangeResource
    RevisionResource r = new RevisionResource(notes, changeData.currentPatchSet());
                                              ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
Target //plugins/autosubmitter:autosubmitter failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.398s, Critical Path: 0.25s

Patch-set: 4
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>